### ISSUE TITLE
Feature - Citizens login

### ISSUE THREAD

**Issue by T-Dawq** [aau-giraf/weekplanner-OLDUI#530]
As a guardian I would like to be able to register pictogram password for citizens so that they can log in themselves

**Is your feature request related to a problem? Please describe.**
Currently, only guardians can log in to the application which means that a guardian will have to log in on a citizen's personal device in order to make a week plan available to the citizen. This is suboptimal for more independent citizens who are able log in themselves.

**Comment from previous year**
[weekplanner#528](https://github.com/aau-giraf/weekplanner/issues/528) is dependent on this. 

**Describe the solution you'd like**
When a Guardian creates a new citizen a Trustee is also created. 

Replace the "Gem boger" button with a "næste" button which take the Guardian to a screen where the Guardian can create a pictogram password for the citizen.

Create the pictogram password screen

Implement pictogram password creation for the citizen

## Subtasks 

- [x] Edit citizen creation view to look like prototype 1
- [ ] Create function for creating new password for citizen with input of list of pictogram ids
- [ ] Screen selection of pictograms, returns a list of pictogram ids
- [ ] Add creation of pictogram login to creation of citizen

Change the "gem borger" button to "næste"
<img width="513" alt="Skærmbillede 2021-09-30 kl  13 13 15" src="https://user-images.githubusercontent.com/58150918/135445116-2e77c53a-a83a-402e-97cb-983c9f245e00.png">

Clicking on the next button should take the guardian to this screen where the pictogram password is created
![Skærmbillede 2021-09-30 kl  20 53 25](https://user-images.githubusercontent.com/58150918/135514069-228c9f23-2688-4fd9-ac37-89c161902f47.png)

See comment below for prototypes (old)

**Comment by dkalaxdk** [comment]
Page for creating a new password for a user.
This page should only be accesible as a guardian, and for a specific citizen.

![image](https://user-images.githubusercontent.com/13720707/94660401-e5cbf180-0305-11eb-97b1-05db23dc3efa.png)

![image](https://user-images.githubusercontent.com/13720707/94660455-f8462b00-0305-11eb-9726-87481fb835de.png)

The password should then be confirmed (By repeating the password)
And error messages should be created, according to whether the password confirmation was correct.
![image](https://user-images.githubusercontent.com/13720707/94660541-11e77280-0306-11eb-849e-a0c9bf2d03e4.png)

![image](https://user-images.githubusercontent.com/13720707/94660573-1e6bcb00-0306-11eb-9134-2b3214e2c7ad.png)
